version : '2'

services:
 tomcat:
  image: quentinv/cmdbuild:latest
  ports:
   - 8080:8080
  restart: always 
  networks:
   - cmdbuild-network
  volumes:
   - ./conf:/usr/local/tomcat/webapps/ROOT/WEB-INF/conf

 pgsql:
  image: postgres:9.3
  restart: always
  environment:
   - POSTGRES_PASSWORD=YOUR_POSTGRES_PASSWORD
  networks:
   - cmdbuild-network
  volumes:
   - ./db:/var/lib/postgresql/data
   
networks:
   cmdbuild-network:
     driver: bridge

